version: '3.8'

services:
  app:
    build:
      context: .
    image: "feedingo:latest"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.docker
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    env_file:
      - ./.env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    image: "feedingo:latest"
    command: celery -A feedingo worker -l info
    volumes:
      - ./:/app
    env_file:
      - ./.env.docker
    depends_on:
      - db
      - redis
      - app

  celery-beat:
    restart: always
    build:
      context: .
    image: "feedingo:latest"
    command: celery -A feedingo beat -l info
    volumes:
      - ./:/app
    env_file:
      - ./.env.docker
    depends_on:
      - db
      - redis
      - app
volumes:
  pgdata: