# Generated by Django 4.1.2 on 2022-10-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_feed_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='rss_url',
            field=models.URLField(unique=True),
        ),
    ]
